### ISSUE TITLE
"Go to bx.in.th" menu UI broken in dark menu bar

### ISSUE THREAD

**Issue by lukyth** [narze/bitbar-bx#2]
The problem can be seen in the gif below.

![bitbar-bx-darkmode-bug](https://user-images.githubusercontent.com/7040242/30143377-a86c20c6-93af-11e7-909e-17d2091772e0.gif)

[macOS Sierra: Make your menu bar and Dock dark](https://support.apple.com/kb/PH25158?locale=en_US&viewlocale=en_US)

**Comment by narze** [comment]
wut :rofl:
